export const OPEN_NAVIGATIONBAR = "OPEN_NAVIGATIONBAR";
export const CLOSE_NAVIGATIONBAR = "CLOSE_NAVIGATIONBAR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
